In [3]:
import numpy as np

In [5]:
loaded = np.load('npdata.npz')

In [9]:
arr1 = np.arange(1,8,2)

In [10]:
arr1

array([1, 3, 5, 7])

In [11]:
arr2 = np.linspace(1,8,num=5)
arr2

array([1.  , 2.75, 4.5 , 6.25, 8.  ])

In [14]:
np.savetxt('data.txt',arr1)

In [15]:
a = np.loadtxt('data.txt')

In [16]:
a

array([1., 3., 5., 7.])

In [17]:
a == arr1

array([ True,  True,  True,  True])